envs:
- key: SECRET_KEY
  value: "Enter a random string of characters"
  type: SECRET
- key: EMAIL_URL
- key: DEFAULT_FROM_EMAIL
- key: GLITCHTIP_DOMAIN
- key: DATABASE_URL
  scope: RUN_TIME
  value: ${glitchtip-db.DATABASE_URL}
- key: REDIS_URL
  scope: RUN_TIME
  value: ${glitchtip-redis.REDIS_URL}
name: glitchtip
services:
- dockerfile_path: Dockerfile
  git:
    branch: master
    repo_clone_url: https://gitlab.com/glitchtip/glitchtip.git
  name: glitchtip-web
workers:
- dockerfile_path: Dockerfile
  git:
    branch: master
    repo_clone_url: https://gitlab.com/glitchtip/glitchtip.git
  name: glitchtip-worker
  run_command: ./bin/run-celery-with-beat.sh
jobs:
- dockerfile_path: Dockerfile
  git:
    branch: master
    repo_clone_url: https://gitlab.com/glitchtip/glitchtip.git
  name: glitchtip-migrate
  run_command: ./manage.py migrate
databases:
- name: glitchtip-db
- name: glitchtip-redis
  engine: REDIS
  production: true
  cluster_name: glitchtip-redis
